//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UDPojok
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItems
    {
        public int item_id { get; set; }
        public int purchase_id { get; set; }
        public int product_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
